jobs:
  test:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./action/run

name: Build

on:
  schedule:
    - cron: "55 2/3 * * *"
